// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WestWindDB.Entities;

public partial class ManifestItem
{
    [Key]
    public int ManifestItemID { get; set; }

    public int ShipmentID { get; set; }

    public int ProductID { get; set; }

    public short ShipQuantity { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("ManifestItems")]
    public virtual Product Product { get; set; }

    [ForeignKey("ShipmentID")]
    [InverseProperty("ManifestItems")]
    public virtual Shipment Shipment { get; set; }
}