// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WestWindDB.Entities;

[Index("CompanyName", Name = "CompanyName")]
[Index("AddressID", Name = "UX_Suppliers_AddressID", IsUnique = true)]
public partial class Supplier
{
    [Key]
    public int SupplierID { get; set; }

    [Required]
    [StringLength(40)]
    public string CompanyName { get; set; }

    [Required]
    [StringLength(30)]
    public string ContactName { get; set; }

    [StringLength(30)]
    public string ContactTitle { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    public int AddressID { get; set; }

    [Required]
    [StringLength(24)]
    public string Phone { get; set; }

    [StringLength(24)]
    public string Fax { get; set; }

    [ForeignKey("AddressID")]
    [InverseProperty("Supplier")]
    public virtual Address Address { get; set; }

    [InverseProperty("Supplier")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}